---
# This playbook deploys an ISPCONFIG install
#
# (c) CarlosM, based on previous example by juancarlos@lacnic.net
# v1 20200708
# ISPCONFIG specifics, https://github.com/inoxio/ansible-role-ispconfig3

# - name: Actualiza usuarios y claves ssh para TODOS
#   hosts: proxmox_cluster, proxmox_vms, proxmox_cts, external_vms
#   become: true
#   roles:
#     - user_maint

# - name: Actualiza los paquetes para todos menos para los nodos hw del cluster
#   hosts: proxmox_vms, proxmox_cts, proxmox_cts_turnkey, external_vms
#   become: true
#   tags: pkgupdate
#   roles:
#     - pkg_update

# - name: Chequeos de sanidad en la red
#   hosts: network
#   connection: network_cli
#   gather_facts: no
#   roles:
#     - network

- name: Instala el ISPCONFIG3
  hosts: all
  roles:
    - users_and_packages
    - inoxio.ispconfig3

