---
# This playbook deploys the whole application stack in this site.
#
# (c) CarlosM, based on previous example by juancarlos@lacnic.net
# v1 20191226

- name: Actualiza usuarios y claves ssh para TODOS
  hosts: proxmox_cluster, proxmox_vms, proxmox_cts, external_vms
  become: true
  tags: xt6users
  roles:
    - user_maint

- name: Instala utiles y paquetes basicos para TODOS
  hosts: proxmox_cluster, proxmox_vms, proxmox_cts, external_vms
  become: true
  tags: xt6utiles
  roles:
   - utiles

- name: Actualiza los paquetes para todos menos para los nodos hw del cluster
  hosts: proxmox_vms, proxmox_cts, proxmox_cts_turnkey, external_vms
  become: true
  tags: xt6pkgupdate
  roles:
    - pkg_update

- name: Chequeos de sanidad en la red
  hosts: network
  connection: network_cli
  gather_facts: no
  roles:
    - network
