---
# This playbook deploys the whole application stack in this site.
#
# (c) CarlosM, based on previous example by juancarlos@lacnic.net
# v1 20191226

- name: Instala utiles y paquetes basicos
  hosts: all
  remote_user: vagrant
  become: true

  roles:
    - utiles
    - grafana_influx