---
# Este playbook configura un ELK 
#     - network
#
# (c) CarlosM, carlos@lacnic.net
#
# v1: 20200803

- name: Instala el ELK, actualiza paquetes y crea usuarios
  hosts: all
  become_user: root
  roles:
    - users_and_packages
    - configure_elk

