# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  NOW = Time.now.strftime("%d.%m.%Y.%H:%M:%S")
  FILENAME = "serial-debug-%s.log" % NOW
  config.vm.provider "virtualbox" do |vb|
     vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]
     vb.customize [ "modifyvm", :id, "--uartmode1", "file",
     File.join(Dir.pwd, FILENAME) ]
     vb.gui = true
     vb.memory = 4096
     vb.cpus = 4
  end

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.define "elk" do |elk|
  	elk.vm.box = "ubuntu/focal64"
  	elk.vm.hostname = "Elk-Stack"
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 9200, host: 9200, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5601, host: 5601, host_ip: "127.0.0.1"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.become = true
    ansible.become_user = "root"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "¡MAQUINA LISTA!"
    echo " "
    ps aux | grep elastic
    echo " "
    ps aux | grep nginx
  SHELL

end
