---
- name: Set if the db should be configured with dbconfig-common
  debconf:
    name: roundcube-core
    question: roundcube/dbconfig-install
    value: true
    vtype: boolean

- name: Set roundcube database-type
  debconf:
    name: roundcube-core
    question: roundcube/database-type
    value: 'mysql'
    vtype: multiselect

- name: Set roundcube mysql-admin-password
  debconf:
    name: roundcube-core
    question: roundcube/mysql/admin-pass
    value: '{{ ispconfig_mysql_root_password }}'
    vtype: password

- name: Set roundcube database-name
  debconf:
    name: roundcube-core
    question: roundcube/db/dbname
    value: 'roundcube'
    vtype: string

- name: Set roundcube mysql-app-password
  debconf:
    name: roundcube-core
    question: roundcube/mysql/app-pass
    value: '{{ roundcube_admin_password }}'
    vtype: password

- name: Set roundcube database-app-password-confirm
  debconf:
    name: roundcube-core
    question: roundcube/app-password-confirm
    value: '{{ roundcube_admin_password }}'
    vtype: password

- name: Set roundcube host
  debconf:
    name: roundcube-core
    question: roundcube/hosts
    value: 'localhost'
    vtype: string

- name: Set roundcube password
  debconf:
    name: roundcube-core
    question: roundcube/pass
    value: '{{ roundcube_admin_password }}'
    vtype: password

- name: Confirm mysql password for roundcube
  debconf:
    name: roundcube-core
    question: roundcube/mysql/app-pass-confirm
    value: '{{ ispconfig_mysql_root_password }}'
    vtype: password

- name: Install required software for roundcube
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - roundcube
      - roundcube-core
      - roundcube-mysql
      - roundcube-plugins
      - javascript-common
      - libjs-jquery-mousewheel
      - php-net-sieve
      - tinymce

# ----------------Configure roundcube----------
- name: Replace localhost entry in config.inc,php
  replace:
    path: /etc/roundcube/config.inc.php
    regexp: "^config['default_host'] ="
    replace: "config['default_host'] = 'localhost';"

- name: Create directory for ssl certificate
  file:
    path: /etc/apache2/certs/{{ roundcube_hostname }}
    state: directory

- name: Check if SSL certificate was created already
  stat:
    path: /etc/apache2/certs/{{ roundcube_hostname }}/fullchain.pem
  register: roundcube_cert

- name: Generate temporary SSL certificate
  command: openssl req
    -x509
    -nodes
    -days 30
    -newkey rsa:2048
    -keyout /etc/apache2/certs/{{ roundcube_hostname }}/privkey.pem
    -out /etc/apache2/certs/{{ roundcube_hostname }}/fullchain.pem
    -subj "/C=US/ST=DummyState/L=DummyTown/O=DummyCompany/OU=Software/CN=dummy-company.com"
  when: not roundcube_cert.stat.exists

- name: Change permission of temporary SSL Key file
  file:
    path: /etc/apache2/certs/{{ roundcube_hostname }}/privkey.pem
    mode: u=rw,g=,o=
  when: not roundcube_cert.stat.exists

- name: Copy roundcube apache vhost
  template:
    src: files/etc/apache2/sites-available/roundcube.vhost.j2
    dest: /etc/apache2/sites-available/roundcube.vhost

- name: Enable roundcube apache vhost
  file:
    src: /etc/apache2/sites-available/roundcube.vhost
    dest: /etc/apache2/sites-enabled/roundcube.vhost
    state: link

- name: Restart apache2
  service:
    name: apache2
    state: restarted
