- name: Copiar la configuracion del proxy a todos los nodos
  copy:
    src: files/00proxy
    dest: /etc/apt/apt.conf.d
    owner: root
    group: root
    mode: 0644
  when: external_host is undefined

- name: Borrar el apt proxy de los hosts externos
  file:
    path: /etc/apt/apt.conf.d/00proxy
    state: absent
  tags: clean
  when: external_host is defined 

- name: Actualizar el cache de apt y hacer un upgrade simple
  apt: 
    update_cache: yes
    upgrade: safe
    autoremove: yes

- name: Borrar el cache de APT para algunos hosts
  command: apt-get clean
  args:
    warn: no
  tags: clean
  when: "'gdns' in inventory_hostname"

- name: Vaciar el journal para los ultimos 3 dias solamente 
  command: journalctl --vacuum-time=3d
  tags: clean
  when: "'gdns' in inventory_hostname"

