---
# Instala las herramientas de base el server

- name: Asegurar que existen grupos adm,sudo,carlos
  group:
    name: "{{ item }}"
    state: present
  loop:
    - adm
    - sudo
    - carlos


- name: Crear usuario carlos
  user: 
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    groups: adm,sudo
    append: yes
  loop:
    - carlos

- name: asegurar que la clave publica de ssh esta subida
  authorized_key:
      user: carlos
      key: '{{ item }}'
      state: present
  with_file:
     - files/carlosm-lacnic-rsa.pub
     - files/carlosm-lacnic-ed25519.pub



