---
# Instala repos y paquetes para el Elk

- name: Instalar dependencias para el apt y repos externos
  shell: | 
     curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
     echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
  args:
    executable: /bin/sh

- name: Instala requisitos para Elk
  apt:
    pkg:
      - default-jre
      - nginx
    update_cache: yes

- name: Instala Elk Mismo
  apt:
    pkg:
      - elasticsearch
      - kibana
      - logstash
    update_cache: no


- name: Crea arbol de directorios 
  file:
    path: '{{ item.dst }}'
    owner: '{{ item.o }}'
    group: '{{ item.g }}'
    state: directory
    mode: '{{ item.mode }}'
  loop:
    - { dst: /etc/kibana, o: kibana, g: kibana, mode: '0755' }
    - { dst: /etc/elasticsearch, o: elasticsearch, g: elasticsearch, mode: '0755' }
    - { dst: /etc/logstash, o: logstash, g: logstash, mode: '0755' }
    

- name: Copia archivos de configuración Elastic & friends
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    owner: '{{ item.o }}'
    group: '{{ item.g }}'
    mode: '{{ item.mode }}'
  loop:
    - { src: files/elasticsearch.yml, dst: /etc/elasticsearch/elasticsearch.yml, o: elasticsearch, g: elasticsearch, mode: '0644' }  
    - { src: files/kibana.yml, dst: /etc/kibana/kibana.yml, o: kibana, g: kibana, mode: '0644' }  
    - { src: files/etc.nginx.sites-available.kibana, dst: /etc/nginx/sites-available/kibana, o: root, g: root, mode: '0644' }      

- name: Configura el acceso a través del NGINX con password 'cocoliso123'
  shell: |
     echo "admin:`openssl passwd -apr1 cocoliso123`" | sudo tee -a /etc/nginx/htpasswd.kibana
     sudo ln -s /etc/nginx/sites-available/kibana /etc/nginx/sites-enabled/kibana

- name: Reinicia procesos varios
  service:
      name: '{{ item }}'
      state: restarted
  loop:
      - elasticsearch
      - kibana
      - logstash
      - nginx

# - name: Detiene el proceso de bind9
#   service:
#     name: bind9
#     state: stopped

# - name: Inicia el proceso de bind9
#   service:
#     name: bind9
#     state: started

# # - name: Deshabilito UFW
# #  ufw:
# #    state: disabled