---
# bind_config_master_zones: [evento.lacnic.net]
bind_config_master_zones: []
# bind_config_master_allow_transfer: [127.0.0.1]
bind_config_master_allow_transfer: []
bind_config_master_forwarders: []
bind_config_recursion: "yes"
bind_config_slave_zones: []
bind_config_forward_zones: []
bind_service_state: started
bind_service_enabled: yes
bind_pkg_state: present
bind_base_zones_path: "/var/lib/bind"
bind_masterzones_path: "masters"
bind_slavezones_path: "slaves"
bind_config_listen_on: any
bind_config_allow_query: ['localhost','45.6.248.0/21','200.0.86.0/23','2001:13c7:7003::/48']
# bind_config_allow_query: []
bind_config_dns64_clients: ['2001:13c7:7003:203::/64']

