---
# ROLE users_and_packages
#
# 

- name: Instalar dependencias para el apt 
  shell: | 
     /usr/bin/apt clean && /usr/bin/apt update
#     apt-get -y install python3.6
  args:
    executable: /bin/sh

- name: Instalar dependencias para el quota support, sudo, bind y otros
  apt: 
    pkg: 
      - bind9utils
      - bind9-host
      - sudo
      - linux-image-extra-virtual
      - cerbot 
    update_cache: yes

- name: Copia archivos de configuración varios
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: files/etc.hosts, dst: /etc/hosts }

- name: Instalar amavis y clamav
  apt: 
    pkg: 
      - amavisd-new
      - clamav
      - clamav-daemon
      - spamassassin
    update_cache: no

- name: Crear el usuario sadm con home en /home/sadm
  user: 
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    home: "/home/{{ item }}"
    append: yes
  loop:
    - sadm

# - name: Copia config. de SNMP
#  template: 
#    src=snmpd.conf.j2 
#    dest=/etc/snmp/snmpd.conf

#- name: Copia /etc/aliases
#  copy:
#    src: files/aliases
#    dest: /etc
#    owner: root
#    group: root
#    mode: 0644

# - name: Deshabilito UFW
#  ufw:
#    state: disabled
